// mu — public API surface for programmatic callers (SDK + tests).
//
// The CLI lives in src/cli.ts. Both the CLI and any SDK consumer go
// through the same exports here so there is exactly one canonical surface.

export {
  AgentDiedOnSpawnError,
  AgentExistsError,
  AgentNotFoundError,
  AgentNotInWorkstreamError,
  adoptAgent,
  closeAgent,
  defaultSpawnLivenessMs,
  deleteAgent,
  composeAgentTitle,
  freeAgent,
  getAgent,
  getAgentByPane,
  insertAgent,
  isValidAgentName,
  listAgents,
  listLiveAgents,
  readAgent,
  refreshAgentTitle,
  resolveCliCommand,
  sendToAgent,
  STATUS_EMOJI,
  spawnAgent,
  updateAgentStatus,
  WorkspacePreservedError,
  type AdoptAgentOptions,
  type AdoptAgentResult,
  type AgentRow,
  type CloseAgentOptions,
  type CloseAgentResult,
  type FreeAgentResult,
  type InsertAgentInput,
  type ListLiveAgentsOptions,
  type LiveAgentsView,
  type SpawnAgentOptions,
} from "./agents.js";
export {
  type AddToArchiveResult,
  type Archive,
  ArchiveAlreadyExistsError,
  ArchiveLabelInvalidError,
  ArchiveNotFoundError,
  type ArchiveSearchHit,
  type ArchiveSourceSummary,
  type ArchiveSummary,
  type ArchivedTaskRow,
  type ListArchivedTasksOptions,
  type RemoveFromArchiveResult,
  type SearchArchivesOptions,
  addToArchive,
  createArchive,
  deleteArchive,
  getArchive,
  isValidArchiveLabel,
  listArchives,
  listArchivedTasks,
  removeFromArchive,
  searchArchives,
} from "./archives.js";
export {
  CURRENT_SCHEMA_VERSION,
  EXPECTED_TABLES,
  SchemaTooOldError,
  defaultDbPath,
  defaultStateDir,
  ensureWorkstreamStateDir,
  openDb,
  workstreamStateDir,
  type Db,
  type OpenDbOptions,
} from "./db.js";
export {
  detectPiStatus,
  extractTail,
  type AgentStatus,
  type DetectedStatus,
} from "./detect.js";
export {
  reconcile,
  type ReconcileMode,
  type ReconcileOptions,
  type ReconcileReport,
} from "./reconcile.js";
export {
  addBlockEdge,
  addNote,
  addTask,
  type BlockEdgeResult,
  claimTask,
  closeTask,
  CrossWorkstreamEdgeError,
  CycleError,
  deferTask,
  deleteTask,
  type DeleteTaskResult,
  getPrerequisites,
  idFromTitle,
  idFromTitleVerbose,
  type IdFromTitleResult,
  slugifyTitle,
  slugifyTitleVerbose,
  type SlugifyResult,
  getTask,
  getTaskEdges,
  type TaskEdges,
  isTaskStatus,
  TASK_STATUSES,
  TASK_STATUS_LIST,
  isValidTaskId,
  type ListReadyOptions,
  type ListTasksOptions,
  listBlocked,
  listGoals,
  listInProgress,
  listNotes,
  listReady,
  listRecentClosed,
  listTasks,
  listTasksByOwner,
  openTask,
  rejectTask,
  releaseTask,
  type RejectDeferOptions,
  type RejectDeferResult,
  STATUSES_TERMINAL_OR_PARKED,
  removeBlockEdge,
  type RemoveBlockEdgeResult,
  reparentTask,
  type ReparentTaskResult,
  resolveActorIdentity,
  searchTasks,
  type SearchTasksOptions,
  setTaskStatus,
  ClaimerNotRegisteredError,
  TaskAlreadyOwnedError,
  TaskExistsError,
  TaskHasOpenDependentsError,
  TaskNotFoundError,
  TaskNotInWorkstreamError,
  updateTask,
  type UpdateTaskOptions,
  type UpdateTaskResult,
  getWaitPollCount,
  resetWaitPollCount,
  setWaitSleepForTests,
  setWaitStuckWarnForTests,
  waitForTasks,
  type TaskWaitOptions,
  type TaskWaitRef,
  type TaskWaitResult,
  type TaskWaitTaskState,
  type AddNoteOptions,
  type AddTaskOptions,
  type ClaimResult,
  type ClaimTaskOptions,
  type EvidenceOption,
  type ReleaseResult,
  type ReleaseTaskOptions,
  type SetStatusResult,
  type TaskNoteRow,
  type TaskRow,
  type TaskStatus,
} from "./tasks.js";
export * as tmux from "./tmux.js";
export { getParallelTracks, type Track } from "./tracks.js";
export {
  destroyWorkstream,
  type DestroyResult,
  ensureWorkstream,
  type ExportResult,
  type ExportWorkstreamOptions,
  exportWorkstream,
  isValidWorkstreamName,
  listWorkstreams,
  summarizeWorkstream,
  type WorkstreamOptions,
  type WorkspaceFailure,
  WorkstreamNameInvalidError,
  type WorkstreamSummary,
} from "./workstream.js";
export {
  ImportBucketInvalidError,
  ImportEdgeRefMissingError,
  ImportFrontmatterParseError,
  ImportLegacyLayoutError,
  type ImportBucketOptions,
  type ImportBucketResult,
  type ImportSourceResult,
  WorkstreamAlreadyExistsError,
  importBucket,
} from "./importing.js";
export {
  type ExportArchiveOptions,
  type ExportArchiveResult,
  type ExportManifest,
  type ExportSource,
  type ExportSourceManifest,
  type ExportTaskEntry,
  exportArchive,
  exportSourceForWorkstream,
  exportSourcesForArchive,
  LegacyExportLayoutError,
  type RenderBucketInput,
  type RenderBucketResult,
  renderToBucket,
} from "./exporting.js";
export {
  assertValidPaneId,
  capturePane,
  currentAgentName,
  currentPaneTitle,
  parseAgentNameFromTitle,
  defaultSendDelayMs,
  isValidPaneId,
  killPane,
  killSession,
  listPanes,
  listPanesInSession,
  listSessions,
  listWindows,
  newSessionWithPane,
  newSession,
  newWindow,
  PANE_ID_RE,
  paneExists,
  resetSleep,
  resetTmuxExecutor,
  selectLayout,
  sendToPane,
  sessionExists,
  setPaneTitle,
  setSleepForTests,
  PaneNotFoundError,
  setTmuxExecutor,
  sleep,
  splitWindow,
  TmuxError,
  type CaptureOptions,
  type NewSessionOptions,
  type NewWindowOptions,
  type SendOptions,
  type SplitWindowOptions,
  type TmuxExecResult,
  type TmuxExecutor,
  type TmuxPane,
  type TmuxSession,
  type TmuxWindow,
} from "./tmux.js";
export {
  type CreateWorkspaceOptions as WorkspaceCreateOptions,
  type FreeWorkspaceOptions as WorkspaceFreeOptions,
  type FreeWorkspaceResult as WorkspaceFreeResult,
  type WorkspaceRow,
  HomeDirAsProjectRootError,
  WorkspaceExistsError,
  WorkspacePathNotEmptyError,
  WorkspaceNotFoundError,
  createWorkspace,
  decorateWithStaleness,
  freeWorkspace,
  getWorkspaceForAgent,
  listWorkspaceOrphans,
  listWorkspaces,
  type WorkspaceOrphan,
  workspacePath,
  workspacesRoot,
} from "./workspace.js";
export {
  type CreateWorkspaceOptions as VcsCreateWorkspaceOptions,
  type CreateWorkspaceResult as VcsCreateWorkspaceResult,
  type FreeWorkspaceOptions as VcsFreeWorkspaceOptions,
  type FreeWorkspaceResult as VcsFreeWorkspaceResult,
  type VcsBackend,
  type VcsBackendName,
  backendByName,
  detectBackend,
  gitBackend,
  jjBackend,
  noneBackend,
  slBackend,
} from "./vcs.js";
export {
  appendLog,
  type AppendLogOptions,
  emitEvent,
  latestSeq,
  listLogs,
  type ListLogsOptions,
  type LogKind,
  type LogRow,
} from "./logs.js";
export {
  captureSnapshot,
  type CaptureSnapshotResult,
  gcSnapshots,
  listSnapshots,
  type ListSnapshotsOptions,
  restoreSnapshot,
  type RestoreSnapshotResult,
  snapshotFileSize,
  SnapshotFileMissingError,
  SnapshotNotFoundError,
  type SnapshotRow,
  SnapshotVersionMismatchError,
  snapshotsDir,
} from "./snapshots.js";
