// mu — public API surface for programmatic callers (SDK + tests).
//
// The CLI lives in src/cli.ts. Both the CLI and any SDK consumer go
// through the same exports here so there is exactly one canonical surface.

export {
  AgentDiedOnSpawnError,
  AgentExistsError,
  AgentNotFoundError,
  AgentNotInWorkstreamError,
  adoptAgent,
  closeAgent,
  defaultSpawnLivenessMs,
  deleteAgent,
  freeAgent,
  getAgent,
  getAgentByPane,
  insertAgent,
  isValidAgentName,
  listAgents,
  listLiveAgents,
  readAgent,
  resolveCliCommand,
  sendToAgent,
  spawnAgent,
  updateAgentStatus,
  WorkspacePreservedError,
  type AdoptAgentOptions,
  type AdoptAgentResult,
  type AgentRow,
  type CloseAgentOptions,
  type CloseAgentResult,
  type FreeAgentResult,
  type InsertAgentInput,
  type ListLiveAgentsOptions,
  type LiveAgentsView,
  type SpawnAgentOptions,
} from "./agents.js";
export {
  CURRENT_SCHEMA_VERSION,
  EXPECTED_TABLES,
  defaultDbPath,
  defaultStateDir,
  ensureWorkstreamStateDir,
  openDb,
  workstreamStateDir,
  type Db,
  type OpenDbOptions,
} from "./db.js";
export {
  detectPiStatus,
  extractTail,
  type AgentStatus,
  type DetectedStatus,
} from "./detect.js";
export { reconcile, type ReconcileOptions, type ReconcileReport } from "./reconcile.js";
export {
  addBlockEdge,
  addNote,
  addTask,
  type BlockEdgeResult,
  claimTask,
  closeTask,
  CrossWorkstreamEdgeError,
  CycleError,
  deleteTask,
  type DeleteTaskResult,
  getPrerequisites,
  idFromTitle,
  slugifyTitle,
  getTask,
  getTaskEdges,
  type TaskEdges,
  isTaskStatus,
  isValidTaskId,
  type ListTasksOptions,
  listBlocked,
  listGoals,
  listNotes,
  listReady,
  listTasks,
  listTasksByOwner,
  openTask,
  releaseTask,
  removeBlockEdge,
  type RemoveBlockEdgeResult,
  reparentTask,
  type ReparentTaskResult,
  searchTasks,
  type SearchTasksOptions,
  setTaskStatus,
  ClaimerNotRegisteredError,
  TaskAlreadyOwnedError,
  TaskExistsError,
  TaskNotFoundError,
  TaskNotInWorkstreamError,
  updateTask,
  type UpdateTaskOptions,
  type UpdateTaskResult,
  waitForTasks,
  type TaskWaitOptions,
  type TaskWaitResult,
  type TaskWaitTaskState,
  type AddNoteOptions,
  type AddTaskOptions,
  type ClaimResult,
  type ClaimTaskOptions,
  type EvidenceOption,
  type ReleaseResult,
  type ReleaseTaskOptions,
  type SetStatusResult,
  type TaskNoteRow,
  type TaskRow,
  type TaskStatus,
} from "./tasks.js";
export * as tmux from "./tmux.js";
export { getParallelTracks, type Track } from "./tracks.js";
export {
  destroyWorkstream,
  type DestroyResult,
  ensureWorkstream,
  isValidWorkstreamName,
  listWorkstreams,
  summarizeWorkstream,
  type WorkstreamOptions,
  WorkstreamNameInvalidError,
  type WorkstreamSummary,
} from "./workstream.js";
export {
  assertValidPaneId,
  capturePane,
  currentPaneTitle,
  defaultSendDelayMs,
  isValidPaneId,
  killPane,
  killSession,
  listPanes,
  listPanesInSession,
  listSessions,
  listWindows,
  newSessionWithPane,
  newSession,
  newWindow,
  PANE_ID_RE,
  paneExists,
  resetSleep,
  resetTmuxExecutor,
  selectLayout,
  sendToPane,
  sessionExists,
  setPaneTitle,
  setSleepForTests,
  PaneNotFoundError,
  setTmuxExecutor,
  sleep,
  splitWindow,
  TmuxError,
  type CaptureOptions,
  type NewSessionOptions,
  type NewWindowOptions,
  type SendOptions,
  type SplitWindowOptions,
  type TmuxExecResult,
  type TmuxExecutor,
  type TmuxPane,
  type TmuxSession,
  type TmuxWindow,
} from "./tmux.js";
export {
  type CreateWorkspaceOptions as WorkspaceCreateOptions,
  type FreeWorkspaceOptions as WorkspaceFreeOptions,
  type FreeWorkspaceResult as WorkspaceFreeResult,
  type WorkspaceRow,
  WorkspaceExistsError,
  WorkspacePathNotEmptyError,
  WorkspaceNotFoundError,
  createWorkspace,
  freeWorkspace,
  getWorkspaceForAgent,
  listWorkspaces,
  workspacePath,
} from "./workspace.js";
export {
  type CreateWorkspaceOptions as VcsCreateWorkspaceOptions,
  type CreateWorkspaceResult as VcsCreateWorkspaceResult,
  type FreeWorkspaceOptions as VcsFreeWorkspaceOptions,
  type FreeWorkspaceResult as VcsFreeWorkspaceResult,
  type VcsBackend,
  type VcsBackendName,
  backendByName,
  detectBackend,
  gitBackend,
  jjBackend,
  noneBackend,
  slBackend,
} from "./vcs.js";
export {
  type AddApprovalOptions,
  ApprovalAlreadyDecidedError,
  ApprovalNotFoundError,
  ApprovalNotInWorkstreamError,
  type ApprovalRow,
  type ApprovalStatus,
  type DecideApprovalOptions,
  type ListApprovalsOptions,
  type WaitApprovalOptions,
  addApproval,
  denyApproval,
  generateApprovalSlug,
  getApproval,
  grantApproval,
  listApprovals,
  timeoutApproval,
  waitApproval,
} from "./approvals.js";
export {
  appendLog,
  type AppendLogOptions,
  emitEvent,
  latestSeq,
  listLogs,
  type ListLogsOptions,
  type LogKind,
  type LogRow,
} from "./logs.js";
